# Generated by Django 4.2.1 on 2023-05-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('C_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=50)),
                ('Contact_Num', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('E_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('E_Name', models.CharField(max_length=50)),
                ('Contact_Num', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPortal',
            fields=[
                ('Payment_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Payment_Type', models.CharField(max_length=50)),
                ('Total_invoice', models.CharField(max_length=50)),
                ('Payment_Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Prod_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Prod_Name', models.CharField(max_length=50)),
                ('Prod_Desc', models.CharField(max_length=50)),
                ('Prod_price', models.CharField(max_length=50)),
                ('Prod_Stock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('S_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Manager_name', models.CharField(max_length=50)),
                ('M_ID', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Num_Workers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_type', models.CharField(max_length=50)),
                ('Payment_ID', models.IntegerField()),
                ('Prod_id', models.IntegerField()),
                ('Store_ID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('C_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms_frontend_app.customer')),
            ],
        ),
    ]
